limit_req_zone $binary_remote_addr zone=leafsentry_general:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=leafsentry_predict:10m rate=2r/s;
limit_conn_zone $binary_remote_addr zone=leafsentry_connections:10m;